# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
# Product name price:integer image_url description
Product.create(name: "Lamy 2000 Ballpoint Pen", price: 62, image_url: "https://static2.jetpens.com/images/a/000/049/49320.jpg?mark64=aHR0cDovL3d3dy5qZXRwZW5zLmNvbS9pbWFnZXMvYXNzZXRzL3dhdGVybWFyay5wbmc&markalign64=dG9wLHJpZ2h0&markscale=19&q=90&s=5ef0831a2a1c3d70e09af05396852bb5", description: "The luxurious Lamy 2000 will be a prized item in any pen collection. This ballpoint pen has a body made of a fiberglass known as Makrolon with brushed stainless steel accents including the spring-loaded clip. The velvety surface lends a warm feeling to the material. The Lamy 2000 is so revered that it is on permanent display at the Museum of Modern Art and has won countless design awards.")
Product.create(name: "Uni-ball Signo UM-151 Gel Pen", price: 3, image_url: "https://static2.jetpens.com/images/a/000/000/307.JPG?mark64=aHR0cDovL3d3dy5qZXRwZW5zLmNvbS9pbWFnZXMvYXNzZXRzL3dhdGVybWFyay5wbmc&markalign64=dG9wLHJpZ2h0&markscale=19&q=90&s=1070287f03e8c27d9e614aa54e5bf4c7", description: "Known for its smooth writing, exceptional ink quality, and outstanding selection of colors and tip sizes, the UM-151 (also known as the Signo DX) is one of our all-time favorite gel pens. Find the perfect one for any task, whether it's writing meticulous notes, marking your calendar, or decorating your scrapbook with colorful captions.")
Product.create(name: "Zebra Disposable Brush Pen", price: 2, image_url: "https://static2.jetpens.com/images/a/000/087/87130.jpg?mark64=aHR0cDovL3d3dy5qZXRwZW5zLmNvbS9pbWFnZXMvYXNzZXRzL3dhdGVybWFyay5wbmc&markalign64=dG9wLHJpZ2h0&markscale=19&q=90&s=109db3661aac96830dca18a936c28e77", description: "Brush pens are great tools for manga artists as well as calligraphers. Convenient and perfect for on the go travel, these pens offer lush black color and varying lines widths depending on applied pressure.")
